services:
  server:
    image: warrenisarobot/web-makemkv-server:0.1.0
    build:
      context:
        server
    ports:
      - 8888:8080
    volumes:
      - /tmp/video:/var/video
      - /tmp/workdir:/var/workdir
  client:
    image: warrenisarobot/web-makemkv-client:0.1.0
    build:
      context:
        client
    ports:
      - 8000:80
