name: makemkv_web
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  leto_generator: ^0.0.1-dev.3
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  csv: ^5.0.1
  http: ^0.13.5
  leto: ^0.0.1-dev.1
  leto_schema: ^0.0.1-dev.3
  leto_shelf: ^0.0.1-dev.1
  logging: ^1.1.1
  path: ^1.8.3
  shelf: ^1.4.0
  shelf_cors_headers: ^0.1.4
  shelf_router: ^1.1.3
